### ISSUE TITLE
About config with masternode issue

### ISSUE THREAD

**Issue by phantanthanh1996** [CooleRRSA/crave#18]
Hello, I am a new. I have some questions about masternode? 
How to config masternodes? Example I want to config .666 Coins reward and masternode activatiob around BLock 3000. Thank you.

**Comment by CooleRRSA** [comment]
I don't understand you.

**Comment by jagottsicher** [comment]
Hard to guess what you are talking about. 

Maybe as a clearification:
To be able to start your node as a masternode it is needed that you deposit exactly 500 Crave in one transaction at the CRAVE node. Due to the fact that you need to send 500 CRAVE + transaction fee you need to calculate that you receive 500 CRAVE with one transaction. than it is possible to active your node as a masternode. 

I guess that you want to activate the masternode and spare transaction fees to let your node become a masternode? That's not how it works.

**Comment by CooleRRSA** [comment]
I think its better to ask help at Discord or Slack channel.

**Comment by phantanthanh1996** [comment]
Sorry, I mean that Could we config parameter in source code to test somethings. Ex. 0.666 coin daily reward to Masternode and We can only activate masternode if and only if the number of blocks is greater than or equal to 3000. Thank you.

**Comment by jagottsicher** [comment]
chance of the source code just as a test is probably off the table, but feel free to fork from this repository, make the changes you wish, compile your own clients and wallets  and/or start a testnet to see, how the changes develop. Afterwards you can request a pull and try to let your changes become part of CRAVE after a long discussion and feedback 
OR 
you just continue with your own version of CRAVE.
